name: Dispatch

on:
  workflow_dispatch:
    inputs:
      flavor:
        required: true
        type: choice
        default: pr
        options:
          - pr
          - nightly

jobs:
  ci-recipe:
    name: Construct CI recipe
    runs-on: ubuntu-latest
    outputs:
      recipe: ${{ steps.ci-recipe.outputs.recipe }}
    steps:
      - uses: actions/checkout@v6

      - id: ci-recipe
        run:
          .ci/ci-recipe.py ${{ inputs.flavor }}

  dispatch:
    name: Dispatch
    needs: ci-recipe
    # uses: DigitalBrains1/test-gha/.github/workflows/ci.yaml@${{ github.head_ref }}
    uses: $/.github/workflows/ci.yaml
    with:
      recipe: ${{ needs.ci-recipe.outputs.recipe }}
    secrets: inherit
