name: Nightly schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "40 10 * * *"
      timezone: "Europe/Amsterdam"

jobs:
  schedule:
    name: Trigger from schedule
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run .github/workflows/nightly.yaml
          gh workflow run .github/workflows/nightly.yaml --ref 1.0
