name: Self-hosted runners test
on:
  push:
  workflow_dispatch:

jobs:
  No-container:
    runs-on: new-director
    steps:
      - run: cat /etc/os-release
  #With-container:
  #  runs-on: self-hosted-compute
  #  container: alpine
  #  steps:
  #    - run: cat /etc/os-release
  im-skipped:
    if: ${{ failure() }}
    runs-on: new-director
    steps:
      - run: echo "I'm being run"
