on:
  pull_request:
  push:
    branches:
      - main
      - "1.0"

jobs:
  trigger_pr:
    name: Trigger PR
    if: github.event_name == 'pull_request'
    # uses: DigitalBrains1/test-gha/.github/workflows/ci.yaml@${{ github.head_ref }}
    uses: $/.github/workflows/ci.yaml
    with:
      flavor: pr
      event_name: ${{ github.event_name }}
      event: ${{ toJSON(github.event) }}
    secrets: inherit


  trigger_push:
    name: Trigger push
    if: github.event_name == 'push'
    uses: $/.github/workflows/ci.yaml
    with:
      flavor: pr
      event_name: ${{ github.event_name }}
      event: ${{ toJSON(github.event) }}
    secrets: inherit
